package methods

const (
	BatchLimit          string = "batch_limit"
	GetVersion          string = "get_version"
	GetHeight           string = "get_height"
	GetTopoheight       string = "get_topoheight"
	GetPrunedTopoheight string = "get_pruned_topoheight"
	GetInfo             string = "get_info"
	GetDifficulty       string = "get_difficulty"
	GetTips             string = "get_tips"
	GetDevFeeThresholds string = "get_dev_fee_thresholds"
	GetSizeOnDisk       string = "get_size_on_disk"

	GetStableHeight     string = "get_stable_height"
	GetStableheight     string = "get_stableheight"
	GetStableTopoheight string = "get_stable_topoheight"
	GetHardForks        string = "get_hard_forks"

	GetBlockAtTopoheight        string = "get_block_at_topoheight"
	GetBlocksAtHeight           string = "get_blocks_at_height"
	GetBlockByHash              string = "get_block_by_hash"
	GetTopBlock                 string = "get_top_block"
	GetBlockDifficultyByHash    string = "get_block_difficulty_by_hash"
	GetBlockBaseFeeByHash       string = "get_block_base_fee_by_hash"
	GetBlockSummaryAtTopoheight string = "get_block_summary_at_topoheight"
	GetBlockSummaryByHash       string = "get_block_summary_by_hash"

	GetBalance                     string = "get_balance"
	GetStableBalance               string = "get_stable_balance"
	HasBalance                     string = "has_balance"
	GetBalanceAtTopoheight         string = "get_balance_at_topoheight"
	GetBalancesAtMaximumTopoheight string = "get_balances_at_maximum_topoheight"

	GetNonce             string = "get_nonce"
	HasNonce             string = "has_nonce"
	GetNonceAtTopoheight string = "get_nonce_at_topoheight"

	GetAsset                   string = "get_asset"
	GetAssetSupply             string = "get_asset_supply"
	GetAssetSupplyAtTopoheight string = "get_asset_supply_at_topoheight"
	GetAssets                  string = "get_assets"

	CountAssets       string = "count_assets"
	CountTransactions string = "count_transactions"
	CountAccounts     string = "count_accounts"
	CountContracts    string = "count_contracts"

	SubmitTransaction      string = "submit_transaction"
	GetTransactionExecutor string = "get_transaction_executor"
	GetTransaction         string = "get_transaction"
	GetTransactions        string = "get_transactions"
	GetTransactionsSummary string = "get_transactions_summary"
	IsTxExecutedInBlock    string = "is_tx_executed_in_block"

	P2PStatus              string = "p2p_status"
	GetPeers               string = "get_peers"
	GetP2PBlockPropagation string = "get_p2p_block_propagation"

	GetMempool           string = "get_mempool"
	GetMempoolSummary    string = "get_mempool_summary"
	GetMempoolCache      string = "get_mempool_cache"
	GetEstimatedFeeRates string = "get_estimated_fee_rates"
	GetEstimatedFeePerKB string = "get_estimated_fee_per_kb"

	GetDAGOrder                string = "get_dag_order"
	GetBlocksRangeByTopoheight string = "get_blocks_range_by_topoheight"
	GetBlocksRangeByHeight     string = "get_blocks_range_by_height"

	GetAccountHistory                string = "get_account_history"
	GetAccountAssets                 string = "get_account_assets"
	GetAccounts                      string = "get_accounts"
	IsAccountRegistered              string = "is_account_registered"
	GetAccountRegistrationTopoheight string = "get_account_registration_topoheight"

	ValidateAddress       string = "validate_address"
	SplitAddress          string = "split_address"
	ExtractKeyFromAddress string = "extract_key_from_address"
	KeyToAddress          string = "key_to_address"
	MakeIntegratedAddress string = "make_integrated_address"
	DecryptExtraData      string = "decrypt_extra_data"

	GetMultisigAtTopoheight string = "get_multisig_at_topoheight"
	GetMultisig             string = "get_multisig"
	HasMultisig             string = "has_multisig"
	HasMultisigAtTopoheight string = "has_multisig_at_topoheight"

	GetContractOutputs                          string = "get_contracts_outputs"
	GetContractLogs                             string = "get_contract_logs"
	GetContractScheduledExecutionsAtTopoheight  string = "get_contract_scheduled_executions_at_topoheight"
	GetContractRegisteredExecutionsAtTopoheight string = "get_contract_registered_executions_at_topoheight"
	GetContractModule                           string = "get_contract_module"
	GetContractData                             string = "get_contract_data"
	GetContractDataAtTopoheight                 string = "get_contract_data_at_topoheight"
	GetContractBalance                          string = "get_contract_balance"
	GetContractBalanceAtTopoheight              string = "get_contract_balance_at_topoheight"
	GetContractAssets                           string = "get_contract_assets"
	GetContracts                                string = "get_contracts"
	GetContractDataEntries                      string = "get_contract_data_entries"
	GetContractTransactions                     string = "get_contract_transactions"
	SimulateContractInvoke                      string = "simulate_contract_invoke"

	GetBlockTemplate string = "get_block_template"
	GetMinerWork     string = "get_miner_work"
	SubmitBlock      string = "submit_block"
	PruneChain       string = "prune_chain"
	RewindChain      string = "rewind_chain"
	ClearCaches      string = "clear_caches"
	Schema           string = "schema"
	Subscribe        string = "subscribe"
	Unsubscribe      string = "unsubscribe"
)
